<?php
if (Mage::helper('sexybookmarks')->isBookmarksEnabled()) {
    $page_title=$this->getLayout()->getBlock('head')->getTitle();
    $page_url=Mage::helper('core/url')->getCurrentUrl();
?>

 
    <?php if (Mage::getStoreConfig('sexybookmarks/options/jquery')) {?>
    <script src="<?php echo $this->getSkinUrl('magazento/sexybookmarks/jquery.js') ?>" type="text/javascript"></script>
    <?php } ?>    
    
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('magazento/sexybookmarks/shr-custom-sprite.css') ?>" type="text/css" media="screen" />
    <script src="<?php echo $this->getSkinUrl('magazento/sexybookmarks/sexy-bookmarks-public.js') ?>" type="text/javascript"></script>

    <div class="sexymagentobookmarks-container">
        <div class="shr-bookmarks-bg-caring">
            <div class="shr-bookmarks shr-bookmarks-expand shr-bookmarks-center" style="margin-left: 15px ! important; height: 32px; display: block; overflow: hidden;">
                <ul class="socials">

                   <?php echo Mage::helper('sexybookmarks')->printBookmarks($page_title,$page_url); ?>
                </ul>
            </div>    
        </div>
        <p class="magazento-powered">Powered by <a href="http://www.magazento.com/english/magento-ext/magazento-extensions" target="_blank">Magento extensions</a></p>
    </div>


<?php } ?>












